from PyQt5 import QtCore, QtGui, QtWidgets
import fit_model_ann
import metrics
from tensorflow.keras.models import load_model
import pandas as pd
import createX_y
import os

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1322, 927)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(490, 0, 391, 61))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(800, 60, 20, 811))
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(5)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setObjectName("line")
        self.lbl_cm = QtWidgets.QLabel(self.centralwidget)
        self.lbl_cm.setGeometry(QtCore.QRect(820, 90, 321, 261))
        self.lbl_cm.setText("")
        self.lbl_cm.setPixmap(QtGui.QPixmap("gorseller/ann/cm.png"))
        self.lbl_cm.setObjectName("lbl_cm")
        self.lbl_loss_acc = QtWidgets.QLabel(self.centralwidget)
        self.lbl_loss_acc.setGeometry(QtCore.QRect(820, 360, 421, 241))
        self.lbl_loss_acc.setText("")
        self.lbl_loss_acc.setPixmap(QtGui.QPixmap("gorseller/ann/loss_acc.png"))
        self.lbl_loss_acc.setObjectName("lbl_loss_acc")
        self.lbl_scores = QtWidgets.QLabel(self.centralwidget)
        self.lbl_scores.setGeometry(QtCore.QRect(820, 610, 501, 251))
        self.lbl_scores.setText("")
        self.lbl_scores.setPixmap(QtGui.QPixmap("gorseller/ann/scores.png"))
        self.lbl_scores.setObjectName("lbl_scores")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(820, 60, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 810, 581, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 850, 761, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 830, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 790, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 770, 741, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(10, 750, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(10, 740, 801, 16))
        self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_2.setLineWidth(5)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setObjectName("line_2")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(290, 170, 281, 81))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.line_epochs = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.line_epochs.setObjectName("line_epochs")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.line_epochs)
        self.label_10 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.line_batch = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.line_batch.setObjectName("line_batch")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.line_batch)
        self.label_11 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.line_earlystop = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.line_earlystop.setObjectName("line_earlystop")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.line_earlystop)
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(290, 135, 261, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.btn_fit_model = QtWidgets.QPushButton(self.centralwidget)
        self.btn_fit_model.setGeometry(QtCore.QRect(290, 260, 141, 31))
        self.btn_fit_model.setObjectName("btn_fit_model")
        self.btn_test_model = QtWidgets.QPushButton(self.centralwidget)
        self.btn_test_model.setGeometry(QtCore.QRect(290, 300, 141, 31))
        self.btn_test_model.setObjectName("btn_test_model")
        self.lbl_roc = QtWidgets.QLabel(self.centralwidget)
        self.lbl_roc.setGeometry(QtCore.QRect(140, 440, 501, 291))
        self.lbl_roc.setText("")
        self.lbl_roc.setPixmap(QtGui.QPixmap("gorseller/ann/roc.png"))
        self.lbl_roc.setObjectName("lbl_roc")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(10, 390, 801, 16))
        self.line_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_3.setLineWidth(5)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setObjectName("line_3")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(350, 410, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(10, 70, 801, 16))
        self.line_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_4.setLineWidth(5)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setObjectName("line_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1322, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        
        self.btn_fit_model.clicked.connect(self.btn_fit_model_click)
        self.btn_test_model.clicked.connect(self.btn_test_model_click)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Artificial Neural Network"))
        self.label.setText(_translate("MainWindow", "Artificial Neural Network"))
        self.label_2.setText(_translate("MainWindow", "Display"))
        self.label_3.setText(_translate("MainWindow", "early_stopping = EarlyStopping(monitor=\'val_sparse_categorical_accuracy\', patience=10, restore_best_weights=True)\n"
""))
        self.label_4.setText(_translate("MainWindow", "checkpoint_cb = ModelCheckpoint(filepath=checkpoint_path, save_best_only=True, save_weights_only=True, monitor=\'val_sparse_categorical_accuracy\')"))
        self.label_5.setText(_translate("MainWindow", "Model Checkpoint :"))
        self.label_6.setText(_translate("MainWindow", "Early Stopping :"))
        self.label_7.setText(_translate("MainWindow", "ann.fit(X_train, y_train, epochs=epochs, batch_size=batch_size, validation_data=(X_val, y_val), callbacks=[early_stopping, checkpoint_cb,csv_logger])"))
        self.label_8.setText(_translate("MainWindow", "Fit Model :"))
        self.label_9.setText(_translate("MainWindow", "Epochs :"))
        self.label_10.setText(_translate("MainWindow", "Batch Size:"))
        self.label_11.setText(_translate("MainWindow", "Early Stopping:"))
        self.label_12.setText(_translate("MainWindow", "Model Eğitimi için gerekli değerler :"))
        self.btn_fit_model.setText(_translate("MainWindow", "Modeli Eğit"))
        self.btn_test_model.setText(_translate("MainWindow", "Modeli Test Et"))
        self.label_14.setText(_translate("MainWindow", "ROC Curve"))
    
    def btn_fit_model_click(self):
        
        self.label_12.setText('Model Eğitiliyor...')
        epochs = int(self.line_epochs.text())
        batch_size = int(self.line_batch.text())
        early_stopping = int(self.line_earlystop.text())
        
        fit_model_ann.fit_ann_with_holdout(epochs, batch_size, early_stopping)
        
        _,_,X_test,_,_,y_test = createX_y.create_train_test_data_for_ann()
        model = load_model('savedModels/model_ann_holdout.keras')
        history_df = pd.read_csv('savedModels/training_history.csv')
        metrics.loss_and_accuracy_graphic(history_df)
        y_pred = model.predict(X_test)
        y_pred = (y_pred > 0.5)

        metrics.ann_metrics(y_test, y_pred)
        
        self.label_12.setText('Model Eğitildi...')
        
        file_paths = ['cm.png', 'loss_acc.png', 'roc.png', 'scores.png']
        labels = [self.lbl_cm, self.lbl_loss_acc, self.lbl_roc, self.lbl_scores]
        
        for path, label in zip(file_paths, labels):
            pixmap = QtGui.QPixmap(os.path.join('gorseller/ann/', path))
            label.setPixmap(pixmap)
            label.setScaledContents(True)

    def btn_test_model_click(self):
        os.system('python screen_modeltest.py')
        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
