from PyQt5 import QtCore, QtGui, QtWidgets
import os


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(469, 484)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 10, 421, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(110, 100, 243, 332))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_veriseti = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_veriseti.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_veriseti.setFont(font)
        self.btn_veriseti.setObjectName("btn_veriseti")
        self.verticalLayout.addWidget(self.btn_veriseti)
        self.btn_ann = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_ann.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_ann.setFont(font)
        self.btn_ann.setObjectName("btn_ann")
        self.verticalLayout.addWidget(self.btn_ann)
        self.btn_random_forest = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_random_forest.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_random_forest.setFont(font)
        self.btn_random_forest.setObjectName("btn_random_forest")
        self.verticalLayout.addWidget(self.btn_random_forest)
        self.btn_knn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_knn.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_knn.setFont(font)
        self.btn_knn.setObjectName("btn_knn")
        self.verticalLayout.addWidget(self.btn_knn)
        self.btn_decision_tree = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_decision_tree.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_decision_tree.setFont(font)
        self.btn_decision_tree.setObjectName("btn_decision_tree")
        self.verticalLayout.addWidget(self.btn_decision_tree)
        self.btn_test_model = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_test_model.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_test_model.setFont(font)
        self.btn_test_model.setObjectName("btn_test_model")
        self.verticalLayout.addWidget(self.btn_test_model)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(210, 80, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 469, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        
        self.btn_veriseti.clicked.connect(self.btn_veriseti_click)
        self.btn_random_forest.clicked.connect(self.btn_random_forest_click)
        self.btn_knn.clicked.connect(self.btn_knn_click)
        self.btn_decision_tree.clicked.connect(self.btn_decision_tree_click)
        self.btn_ann.clicked.connect(self.btn_ann_click)
        self.btn_test_model.clicked.connect(self.btn_test_model_click)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Epileptic Seizure Recognition"))
        self.label.setText(_translate("MainWindow", "Epileptic Seizure Recognition"))
        self.btn_veriseti.setText(_translate("MainWindow", "Veriseti İşlemleri"))
        self.btn_ann.setText(_translate("MainWindow", "Yapay Sinir Ağı"))
        self.btn_random_forest.setText(_translate("MainWindow", "Random Forest"))
        self.btn_knn.setText(_translate("MainWindow", "K-Nearest Neighbor"))
        self.btn_decision_tree.setText(_translate("MainWindow", "Decision Tree"))
        self.btn_test_model.setText(_translate("MainWindow", "Modeli Test Et"))
        self.label_2.setText(_translate("MainWindow", "Modeller"))
        
    def btn_veriseti_click(self):
        os.system("python screen_veri.py")
    def btn_decision_tree_click(self):
        os.system("python screen_desicionTree.py")
    def btn_random_forest_click(self):
        os.system("python screen_randomForest.py")
    def btn_knn_click(self):
        os.system("python screen_knn.py")
    def btn_ann_click(self):
        os.system("python screen_ann.py")
    def btn_test_model_click(self):
        os.system("python screen_modeltest.py")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
